language: node_js
node_js: 8
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "project-details:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: C05aMvaRGGawrKA8+tpytv69Mj0bT52gGnA6cb0OBmix4mYpKCsUTXQeUUtB1dgjqrm6EnsP8q19g7Tp8qNewkDvV9y9LkjxIVJm+/ZwF07NG6uyX5rjkGjxRhK5fd/K4lPnqIeBM8ht91ivpRhvtVfYY71z5j07NB/pW4C/Lk0NEdlQEUB2d9PbrfNd23QphKN6UgCYzwTIhSjESiSc59emwfCDXurzKyxKri+2jyPwJMr5Lc79SYvbxKn+iGi8ALHEGgTXQm9lxT3F222TZtZQnh/oBiuz4A52eqA43Ueh0ol/78seWfagdAFdEf7tUTiL+t1yuKq/S7ECuxAeR008jqPTdYcX2ikdtkCWqPlyypJyTAog3E7myhf2CBjLhRV3G7abkuVovjkk/H25ZLyD6BBTZYdMHipH+SmtD9gelStOO612P/AkwRjeT0KrC0gFJyUxzzwFspk8vBo6HnbHBVM86wQqa21wyTGUkbD4Uk04ISJjzPX4SzDLfu3FY3thHL3ma3dVI5V5fy0z3yKhYI5S/4Aj9pPIxwDBH1EDZZ/whVGqMB0WxNsk3iqe49Sck9vguiN8EM+JD6SmiMOmMxhyLWKNjQ1IQNSdjxcCOLPT4B1uI/aD82W6+cHYDH6Ju2l/M3FyWc++OgQpg2OJLasasxf4gHdLr0Gx63o=
  - secure: V7pqZfrj0ZoFHjc+/8MnboLkNNrxGOZwubFiKnmQCfELDFwgjKFBnAzhhMH+F12mCZopPdZoMPGbaaoZLUUMdB8GXsw61Rc5U3JjZzhYwanhTDK7b/4D0aZ56uxnUw2YoofaegiBuliaG1EUQz1RGIzBCDnRIXEH+VJ5jhHjWcpvufTovII/YSduzFiv2Rn99J9XdCDmwKS5a/Fs9fwQAAm0GHBemEuAW8ififJbKyzPiVKYAneb3ZX7lHZw3NtAaliwKltJcloF/l58nJYlafobT3QdzbdYoHyyqZqxqKJ+CY5fzoIYcf4o4bBtk2lB8vnP3kzUJucx8MYhCEBP9l55N9I87dNT1rFM3kTttS9OzD+OBYdRn3J4sH7DQNeIrRGcSdsVBOqF2CAHR1WKFZNJu0NpUWFTzVSLaFtdfCbonldN0g8mGaPmf/5A7LtSPJKOCXqDuOLArU1yyZE4LqJWRBEukqf/BtZyoSzFIW7J0x4t9gykQ+ypWPvGCTI6rrWKzldV8WVIcN2ot/iRVodB7jB2nYLAqsvAn23OsO3oiDW/SQB3QcKz6A0ArDcy//x8XYsbOa72nZZzs4TxY9I2YPI9BAVJ7zhPRTo9ZyO1gMvwAmXAEII6/5q2FJpz9IKrfxDz4pLOgIpumJcdr2ww7xjjc/vzhjGWtLFov44=
